#pragma once

#include <QThread>

#include "../Resources/SIMCONNECT.h"
#include "../Utilities/UTILS.h"

class IAFCS_CONTROLLER : public QThread
{
public:
	HANDLE hSimConnect = NULL;

	enum DATA_DEFINITIONS
	{
		DEFINITION_ELEVATOR_POSITION,
		DEFINITION_AILERON_POSITION,
		DEFINITION_FLIGHT_PARAMETERS,
		DEFINITION_GENERAL_ENG_THROTTLE_LEVER_POSITION
	};

	struct TYPE_ELEVATOR_POSITION
	{
		double ELEVATOR_POSITION;
	} ELEVATOR_POSITION;

	struct TYPE_AILERON_POSITION
	{
		double AILERON_POSITION;
	} AILERON_POSITION;

	struct TYPE_JOYSTICK_INPUT
	{
		double X_AXIS;
		double Y_AXIS;
	} JOYSTICK_INPUT;

	struct {
		bool AUTOTHROTTLE_INHIBIT = false;
		bool AUTOTHROTTLE_SPEED = false;
		bool COMMAND_PITCH = false;
		bool COMMAND_ROLL = false;
		bool DIRECT_MODE = false;
	} AFCS_ENGAGEMENT_STATUS;

	struct TYPE_FLIGHT_PARAMETERS
	{
		double GENERAL_ENG_THROTTLE_LEVER_POSITION;
		double ROTATION_VELOCITY_BODY_X;
		double ROTATION_VELOCITY_BODY_Y;
		double ROTATION_VELOCITY_BODY_Z;
		double PLANE_ALT_ABOVE_GROUND;
		double PLANE_PITCH_DEGREES;
		double PLANE_BANK_DEGREES;
		double PLANE_HEADING_DEGREES_TRUE;
		double INCIDENCE_ALPHA;
		double AIRSPEED_INDICATED;
		double VERTICAL_SPEED;
		double OVERSPEED_WARNING;
		double INDICATED_ALTITUDE;
		double G_FORCE;
	} FLIGHT_PARAMETERS;

	struct TYPE_GENERAL_ENG_THROTTLE_LEVER_POSITION
	{
		double GENERAL_ENG_THROTTLE_LEVER_POSITION_1;
		double GENERAL_ENG_THROTTLE_LEVER_POSITION_2;
		double GENERAL_ENG_THROTTLE_LEVER_POSITION_3;
		double GENERAL_ENG_THROTTLE_LEVER_POSITION_4;
	} GENERAL_ENG_THROTTLE_LEVER_POSITION;
};

