#include "AFCS_COMMAND_ROLL.h"

AFCS_COMMAND_ROLL::AFCS_COMMAND_ROLL(IAFCS_CONTROLLER* AFCS_CTL) : IAFCS_MODULE_THREADED(AFCS_CTL)
{
	HEADING_CONTROLLER = new PID_CONTROLLER_RESTRICTED_OUTPUT(HEADING_CORRECTION_RATE, 0, 0, DegreesToRadians(-25), DegreesToRadians(25));
	SURFACE_CONTROLLER = new PID_CONTROLLER_RESTRICTED_OUTPUT(AILERON_CORRECTION_RATE, 0, 0, -1.0, 1.0);
}

void AFCS_COMMAND_ROLL::RunModuleLogic()
{
	/// Heading controller output is adjusted according to the difference between target heading and actual heading
	double HEADING_ERROR = HEADING_SELECT - RadiansToDegrees(AFCS_CTL->FLIGHT_PARAMETERS.PLANE_HEADING_DEGREES_TRUE);
	double HEADING_CONTROLLER_OUTPUT = HEADING_CONTROLLER->Update(HEADING_ERROR);

	/// Aileron position is adjusted according to the difference between target bank angle and actual bank angle
	double BANK_ANGLE_ERROR = HEADING_CONTROLLER_OUTPUT - -AFCS_CTL->FLIGHT_PARAMETERS.PLANE_BANK_DEGREES;
	double AILERON_POSITION = SURFACE_CONTROLLER->Update(BANK_ANGLE_ERROR);

	/// Send updated aileron position to the simulator
	AFCS_CTL->AILERON_POSITION.AILERON_POSITION = AILERON_POSITION;
	SimConnect_SetDataOnSimObject(AFCS_CTL->hSimConnect, AFCS_CTL->DEFINITION_AILERON_POSITION, SIMCONNECT_OBJECT_ID_USER, 0, 1, sizeof(AFCS_CTL->AILERON_POSITION), &AFCS_CTL->AILERON_POSITION);
}
