#include "AFCS_AUTOTHROTTLE.h"

AFCS_AUTOTHROTTLE::AFCS_AUTOTHROTTLE(IAFCS_CONTROLLER* AFCS_CTL) : IAFCS_MODULE(AFCS_CTL)
{
	SURFACE_CONTROLLER = new PID_CONTROLLER_RESTRICTED_OUTPUT(THROTTLE_CORRECTION_RATE, 0, 0, 21, 85);
}

void AFCS_AUTOTHROTTLE::RunModuleLogic()
{
	/// Throttle controller output is adjusted according to the difference between target speed and actual speed
	double SPEED_ERROR = SPEED_SELECT - AFCS_CTL->FLIGHT_PARAMETERS.AIRSPEED_INDICATED;
	double THROTTLE_CONTROLLER_OUTPUT = SURFACE_CONTROLLER->Update(SPEED_ERROR);

	/// Send updated throttle levers position to the simulator
	AFCS_CTL->GENERAL_ENG_THROTTLE_LEVER_POSITION.GENERAL_ENG_THROTTLE_LEVER_POSITION_1 =
		AFCS_CTL->GENERAL_ENG_THROTTLE_LEVER_POSITION.GENERAL_ENG_THROTTLE_LEVER_POSITION_2 =
		AFCS_CTL->GENERAL_ENG_THROTTLE_LEVER_POSITION.GENERAL_ENG_THROTTLE_LEVER_POSITION_3 =
		AFCS_CTL->GENERAL_ENG_THROTTLE_LEVER_POSITION.GENERAL_ENG_THROTTLE_LEVER_POSITION_4 =
		THROTTLE_CONTROLLER_OUTPUT;
	SimConnect_SetDataOnSimObject(AFCS_CTL->hSimConnect, AFCS_CTL->DEFINITION_GENERAL_ENG_THROTTLE_LEVER_POSITION, SIMCONNECT_OBJECT_ID_USER, 0, 1, sizeof(AFCS_CTL->GENERAL_ENG_THROTTLE_LEVER_POSITION), &AFCS_CTL->GENERAL_ENG_THROTTLE_LEVER_POSITION);
}
