#include "PID_CONTROLLER.h"

PID_CONTROLLER::PID_CONTROLLER(double PROPORTIONAL_COEFFICIENT, double INTEGRAL_COEFFICIENT, double DERIVATE_COEFFICIENT)
{
	this->PROPORTIONAL_COEFFICIENT = PROPORTIONAL_COEFFICIENT;
	this->INTEGRAL_COEFFICIENT = INTEGRAL_COEFFICIENT;
	this->DERIVATE_COEFFICIENT = DERIVATE_COEFFICIENT;
	this->OLD_ERROR = 0;
	this->INTEGRAL_ERROR = 0;
}

double PID_CONTROLLER::Update(double INPUT)
{
	INTEGRAL_ERROR += INPUT;
	double DERIVATE_ERROR = INPUT - OLD_ERROR;

	double PROPORTIONAL = PROPORTIONAL_COEFFICIENT * INPUT;
	double INTEGRAL = INTEGRAL_COEFFICIENT * INTEGRAL_ERROR;
	double DERIVATE = DERIVATE_COEFFICIENT * DERIVATE_ERROR;

	return PROPORTIONAL + INTEGRAL + DERIVATE;
}
